version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/LSM
permissions:
  - object: /home/ec2-user/LSM
    owner: ec2-user
    group: ec2-user
    mode: 755


hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu